[package]
name = "euclid"
version = "0.6.3"
authors = ["The Servo Project Developers"]
description = "Geometry primitives"
documentation = "http://doc.servo.org/euclid/"
repository = "https://github.com/servo/euclid"
license = "MIT / Apache-2.0"

[features]
default = []
plugins = ["serde", "serde_macros", "heapsize", "heapsize_plugin"]
unstable = []

[dependencies]
rustc-serialize = "0.3.2"
num = {version = "0.1.24", default-features = false}
log = "0.3.1"
serde = {version = "0.7", optional = true}
serde_macros = {version = "0.7", optional = true}

[dependencies.heapsize]
version = ">=0.2, <0.4"
optional = true

[dependencies.heapsize_plugin]
version = "0.1.3"
optional = true

[dev-dependencies]
rand = "0.3.7"
