[package]
name = "euclid"
version = "0.14.2"
authors = ["The Servo Project Developers"]
description = "Geometry primitives"
documentation = "https://docs.rs/euclid/"
repository = "https://github.com/servo/euclid"
keywords = ["matrix", "vector", "linear-algebra", "geometry"]
categories = ["science"]
license = "MIT / Apache-2.0"

[features]
minted = ["mint"]
unstable = []

[dependencies]
heapsize = "0.4"
num-traits = {version = "0.1.32", default-features = false}
log = "0.3.1"
mint = {version = "0.3", optional = true}
serde = "0.9"

[dev-dependencies]
rand = "0.3.7"
serde_test = "0.9"
