[package]
name = "euclid"
version = "0.12.0"
authors = ["The Servo Project Developers"]
description = "Geometry primitives"
documentation = "https://docs.rs/euclid/"
repository = "https://github.com/servo/euclid"
keywords = ["matrix", "vector", "linearalgebra", "geometry"]
categories = ["science"]
license = "MIT / Apache-2.0"

[features]
unstable = []

[dependencies]
heapsize = "0.3"
rustc-serialize = "0.3.2"
num-traits = {version = "0.1.32", default-features = false}
log = "0.3.1"
serde = "0.9"

[dev-dependencies]
rand = "0.3.7"
serde_test = "0.9"
